feat(wifi-interface): interface detection and validation

diff --git a/create-hotspot b/create-hotspot
--- a/create-hotspot
+++ b/create-hotspot
@@ -1,10 +1,24 @@
-#! /bin/sh
-
-set -e
+#!/bin/sh
 
 WIFI_INTERFACE=$(snapctl get wifi-interface)
 SSID=$(snapctl get ssid)
 PASSWORD=$(snapctl get password)
 
-nmcli d wifi hotspot ifname $WIFI_INTERFACE ssid "$SSID" password "$PASSWORD"
+retries=5
+i=1
+while [ $i -le $retries ]; do
+  nmcli d wifi hotspot ifname $WIFI_INTERFACE ssid "$SSID" password "$PASSWORD"
+
+  # Check the exit code
+  if [ $? -eq 0 ]; then
+    return 0
+  fi
+
+  echo "Attempt $i failed. Retrying to create the hotspot in 5 seconds..." >&2
+  sleep 5
+  i=$((i + 1))
+done
+
+echo "Failed to create the hotspot." >&2
+return 1
 
